### ISSUE TITLE
Import forms into 4D v14

### ISSUE THREAD

**Issue by MCBL** [4D/vc-framework-v14#2]
Hello,

we're working with 4D and are searching a way to export and **import forms**.
Your *VC_Framework* plugin fit our needs of exporting. What about importing?

Do you think today's 4D methods allows us to import forms? I don't find how until now.

Thanks for your work!

Have a nice day,

**Comment by jay-jay** [comment]
Were you able to find a solution importing methods/forms to 4D?

**Comment by MCBL** [comment]
No, I think 4D itself don't want us to do it now.

**Comment by tpenner** [comment]
Sorry, importing is not a feature of this component. 

This goal of this component was to get the code objects out of 4D and into text files so that developers could take advantage of diffing tools.

[Quote](https://github.com/4D/vc-framework-v14#description)
> The VC_Framework component facilitates automatic export of all methods and forms (collectively referred to as "assets") from a 4D host database to text files on disk. If the host database is under revision control, these text files are suitable for committing to the repository, thus giving the developer a granular ability to track changes to assets over time.

In order for importing forms back into 4D to work there would need to be a new command (feature request) to create forms and form objects via code.  

Note: the [original feature request](http://forums.4d.fr/Post/EN/11356930/1/11356931#11356931) that makes exporting forms possible was for export only.
